name: SolarCredit
main: gg.solarmc.solarcredits.SolarCredit
version: 1.0
authors: [ herobrine99dan, zone_infinity ]
commands:
   credits:
      description: The only command of SolarCredit
      usage: /<command>